<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>DevHub.Sdk.IntegrationTests</RootNamespace>
    <AssemblyName>DevHub.Sdk.IntegrationTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DevHub.Sdk\DevHub.Sdk.csproj" />
    <ProjectReference Include="..\..\..\..\host\src\DevHub.Host\DevHub.Host.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
