<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>DevHub.Host</RootNamespace>
    <AssemblyName>DevHub.Host</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevHub.Core\DevHub.Core.csproj" />
  </ItemGroup>

  <Target Name="NormalizeCoreProjectReferenceConfiguration" AfterTargets="AssignProjectConfiguration">
    <ItemGroup>
      <ProjectReferenceWithConfiguration Update="..\DevHub.Core\DevHub.Core.csproj">
        <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
        <SetConfiguration>Configuration=$(Configuration)</SetConfiguration>
        <SetPlatform>Platform=$(Platform)</SetPlatform>
      </ProjectReferenceWithConfiguration>
      <_ProjectReferenceWithConfiguration Update="..\DevHub.Core\DevHub.Core.csproj">
        <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
        <SetConfiguration>Configuration=$(Configuration)</SetConfiguration>
        <SetPlatform>Platform=$(Platform)</SetPlatform>
      </_ProjectReferenceWithConfiguration>
    </ItemGroup>
  </Target>

</Project>
