<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>DevHub.Sdk.ConformanceAdapter</RootNamespace>
    <AssemblyName>DevHub.Sdk.ConformanceAdapter</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Json.Net.Unity3D" GeneratePathProperty="true" />
    <ProjectReference Include="..\..\src\DevHub.Sdk\DevHub.Sdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Remove="Newtonsoft.Json" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(PkgJson_Net_Unity3D)\lib\net35\Newtonsoft.Json.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
