<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>DevHub.Sdk.ConformanceAdapter</RootNamespace>
    <AssemblyName>DevHub.Sdk.ConformanceAdapter</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Json.Net.Unity3D" GeneratePathProperty="true" />
    <ProjectReference Include="..\..\src\DevHub.Sdk\DevHub.Sdk.csproj" />
  </ItemGroup>

</Project>
