<Project>
  <Import Project="$(MSBuildThisFileDirectory)../../eng/Version.props" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>$(DevHubVersion)</Version>
    <AssemblyVersion>$(DevHubAssemblyVersion)</AssemblyVersion>
    <FileVersion>$(DevHubFileVersion)</FileVersion>
    <InformationalVersion>$(DevHubInformationalVersion)</InformationalVersion>
  </PropertyGroup>
</Project>
